### ISSUE TITLE
Make sure username and password are encoded for database download

### ISSUE THREAD

**Issue by lramarojaona** [ec-europa/toolkit#132] opened 2019-02-14 17:00 UTC
Hi,

I just ran into an issue where the download of the database was failing, because of special characters in the password.
I had to encode them in my _build.developer.props_ file to be able to download the database.

Here's an example of such a password: **passwordwith@and#**
This ends up like this: **https://username:passwordwith@and#@xxxxx.xxx/xxx.sql**

I had to encode the special characters in _build.developer.props_:
- \# => %23
- @ => %40

This ends up to be nasty, would it be possible to encode them automatically at run-time?

Thanks!

**Comment by jonhy81** [comment] 2019-04-16 14:40
Hi @lramarojaona , can you provide me more information in order to reproduce this issue. I checked all my pass for ASDA and cannot found any special char there. In which project are you having issues?

**Comment by lramarojaona** [comment] 2019-04-16 15:34
Hi @jonhy81 , details have been sent through email.

**Comment by jonhy81** [comment] 2019-05-28 08:13
Related to https://github.com/ec-europa/toolkit/pull/150

**Comment by ghost** [comment] 2019-09-04 05:58
Closing issue since password has now been url encoded.

**Closed by ghost** 2019-09-04 05:58 UTC
